---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dashboards-tls
spec:
  secretName: dashboards-tls
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-acme-http01
  commonName: "{{ .Values.httpbinDomain }}"
  dnsNames:
    - "{{ .Values.httpbinDomain }}"
    - "{{ .Values.traefikAuthDomain }}"
    - "{{ .Values.traefikDashboardDomain }}"
    - "{{ .Values.grafanaDashboardDomain }}"
    - "{{ .Values.prometheusDashboardDomain }}"