---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  annotations: {}
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--api"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      traefik:
        expose: false
      metrics:
        # -- When using hostNetwork, use another port to avoid conflict with node exporter:
        # https://github.com/prometheus/prometheus/wiki/Default-port-allocations
        port: 9982
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
