---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls-example-com
spec:
  secretName: wildcard-tls-example-com
  issuerRef: 
    kind: ClusterIssuer
    name: cloudflare-acme-dns01
  commonName: "{{ .Values.wildCardDomain }}"
  dnsNames:
    - "{{ .Values.wildCardDomain }}"